language: node_js
node_js:
  - "4.2"
sudo: false
cache:
  directories:
  - "/home/travis/.local"
before_install:
- npm config set spin false
install:
- pip install --user -U awscli
- npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run test-ci
deploy:
  - provider: script
    script: make publish
    on:
      tags: true

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJ2FJKT7KSNFRPWCQ
    - secure: "AFB8OtuKeqmbkCAwHmthc78yQd+o62twi4sTiNAi7OhRiQMYYxYQeNee3tJSVXOvnQ/nGyat7X5oQFVx0mWm560eQwE/8XyZPKI1tfT9Wd0zOYYprV7m8rMg1sxaEI3zwbF+f2JDcZxY6xvV2isXmGlYF6fJNyIig3GPBTEON571Al2OXqhwXH+Ey068KAYReUf2q4WLXGea+bcFWo2+Al8PM9AqmYmqfKoIuI8muVvpcSAfJd0+nZZZr9YQvdQ+iXy1wkvlv5S3T2TTRSovAO20wyMf5ATruL0aCzPd2JZor+UKKP8sciI48cGJACqY9HBJAjxGiXgSKWeZ5oTxDXIyz/okH9RY/Bjf5Z0G4qjhFvPUdqoWcaFsnyt/E+YCTS0qc5TwgFoicR6Ug+iF94QGW2PGmd4mMV8q2G9tGJ6NiArGkdIJbjgKT1uJVou9aVCKnuvWq8rFLaj4jOVkPNX24OUo9MSzrr4JWekBA6UzNba5cfW9CMQ+MvLmOt2LPDZYiDeVxeW2Kphi4xly8X+0hzf0Z6YvKN6qe8tJHCO0E5j9VRSWGRMAOKoZiP4X5IsFzxvIoc8Hu8slMmz2u6PZNjDTa1/v2jpE8UMSh7YewqOWf0Vv2jQsvzD+7e5MoE1adslFxGTzmoYLSLyynC7rwd9+bMuolNVJ66FQf9w="

notifications:
  slack:
    secure: "CmKe347SI3j55sa444/T0xSGuGXr41lkYIKzcNIxDNGAR+5C8LyS+B2mkj9yJx/ZDDAXuk0BIOB5G3njPckAbdQqBNSetYmtp0rj58rnkHT3Tc5YT4mjM0UVqW/JmVDmwSk2vihvYe/kaFtLwJLUhyGDkHEmQq93zKPnG/4XR/24I6p/A8QSJ+DDFX9ksIS7ChpPRmfsl5+Z5qVUE8li8N7vUWOVRiBvUNlMiKb97s1+Zd7sCpRyy9u51RNf45yYpaHtz+yClCbGPcB7mfDucluYdNJRvV/iELS9r8Nf+lueRcWoRw5lcGL+r4Ik5kUzp+VAOKylvh4SSGJ1cjNu/SOJ+fsAV03C65WiFhlZXkHDz3FVgvR3+N3PwzQ+aEHk5YcQYqjEaiqOBnr4oCqRBvUJ0P+XqObMcT8fvRVQFHQ3BZhLLGFfU8LUcAfUZbcengcAtJFVEEwqnavKCR22a9BhNDiAMH1loBYOXQ5cvoAC9zoUjoKyaXSP0Jy59ZEFosTI/wdZH2IwnV+9gsooV/oyrQQ7JhgVJlHGAn8p9V+RPOaUItYvwCip5ELazvsZSRaRRSi1a0N8E2XzlluEAaCThBQf59WXca7btIGlY1xf128kvmzB+SZWeEdstQoxVANZfrFTB22NdhznEaQhk/qI/xf8Sj83EEUAKnBqlfY="
